### ISSUE TITLE
README broken links

### ISSUE THREAD

**Issue by peppermintpatty5** [AOrps/SigMal#23]
The links on [educational-material/README.md](https://github.com/AOrps/SigMal/blob/99503e1b2a8502507ae0de5c11d161387445e4d5/educational-material/README.md) are broken due to a questionable directory restructure in e78c1e7e1611bf56bde3a8f75007386a0207c5a4.

**Comment by AOrps** [comment]
Bug Fixed in Commit a12cb7ae951d51be253e74722595ab5374414056
